# Порт работы микросервиса
server:
  port: 8081

# Настройки spring
spring:
  application:
    name: user-driver-service
  datasource: # Подключение в БД
    url: jdbc:postgresql://localhost:5432/user_driver_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa: # Настройки hibernate
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# LOGGING
logging:
  level:
    root: info                            # уровень для корневого логгера
    com.*: debug  # уровень для пользовательского логгера
  file:
    path: logs/user-driver-service/       # путь для файлов логов
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7