# Порт работы микросервиса
server:
  port: 8081

# Настройки spring
spring:
  application:
    name: user-driver-service
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    clear-checksums: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user_driver_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: user-driver-consumers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.orderrideservice.event,com.yourcompany.commonevents.dto,java.util,java.lang"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      driver-events: driver-events
      ride-events: ride-events
      payment-requests: payment-requests
      payment-events: payment-events

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# LOGGING
logging:
  level:
    root: info
    com.userdriverservice.*: debug
    liquibase: debug
  file:
    path: logs/payment-billing-service/
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

