# Порт работы микросервиса
server:
  port: 8081

# Настройки spring
spring:
  application:
    name: user-driver-service
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    clear-checksums: true
  datasource: # Подключение в БД
    url: jdbc:postgresql://localhost:5432/user_driver_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: kafka:9092
    topics:
      driver-events: driver-events
      ride-events: ride-events
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa: # Настройки hibernate
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# LOGGING
logging:
  level:
    root: info    # уровень для корневого логгера
    com.userdriverservice.*: debug  # уровень для пользовательского логгера
    liquibase: debug  # уровень для логгера Liquibase
  file:
    path: logs/payment-billing-service/       # путь для файлов логов
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

